### PR TITLE
Feat/advance

### PR DESCRIPTION
**Pull request by xquanluu**
To Fix/ add new feature
https://github.com/jambonz/chrome-extension-dialer/issues/9
https://github.com/jambonz/chrome-extension-dialer/issues/11
https://github.com/jambonz/chrome-extension-dialer/issues/10

### CODE REVIEW

**Comment by davehorton** [comment]
when we click Save on the Advanced Settings tab, we should verify that the credentials work by submitting some type of request to the server.  Something like retrieving the applications. Currently, I click Save and I see no network traffic in the devtools network page, and there is also no visual cue, like a check mark, that the credentials worked.  We need something similar to how we test speech creds and show a checkmark.  Retrieiving the applications for the account and verify we get a 200 OK back should be enough

**Review by davehorton — CHANGES_REQUESTED** [review]
Currently, in order to make the api calls work, I must add the API server base URL in this format
```
https://jambonz.me/api/v1
```
Please make the code able to accept as well any of the following inputs, and modify as needed before making api calls so that they work
```
https://jambonz.me/api
https://jambonz.me
jambonz.me
```

I think people are likely to try any of these and it will be confusing if they don't work.  We can easily add the https scheme if needed, as well as the `api` and `v1`

**Review by davehorton — CHANGES_REQUESTED** [review]
When we dial an app directly, the number input field gets filled with app-{uuid}
image

I realize that this is the sip uri we are using, but it looks kind of weird to put it in the dial input field.  

Also, the dialing UI briefly appears and says "Dialing app-{uuid}".  Could we change that dialing UI to instead say "Dialing {app name"}?

As far as the number input field, could we simply leave it blank when dialing an application (or a queue)?

**Comment by davehorton** [comment]
- Change "History" to "Calls"
- On that page, switch the order of tabs so "Recent" is on the left and "Saved" is on the right, and Recent is the one you see when you first click on "Calls"
- Use trash can icon on Saved page to delete from Saved.  Mouseover should say "Delete"
- in the dialer SIP Display Name should be optional
- When saving settings, I think we need more than "Settings saved successfully".  I think we need to know that they work also, not just saved
- If I click an app to dial, you have made the change to show the app name and not the sid, and also not to populate it into the input.  However, if I then go to recent calls and click it, I again see the Dialing app-{sid} and it is populated into the input.

**Comment by davehorton** [comment]
- display name still required
- Jambonz Account Sid still has placeholder text
- When there are no saved calls it says "No Call History".  It should say "No saved calls"
- when I click queues I get an empty dropdown, instead it should say "No calls in queue"
- the mouseover of queues should say "Take a call from queue"
- the mouseover of apps should say "Call an application" (not Call to an application)
- the mouseover of users should say "Call an online user"

**Comment by davehorton** [comment]
ok, here is a regression bug.

In Calls/Recent I clicked to save a call to the Saved section.  Immediately, the icon in the Recent section now changes to a trash can.
image

This is wrong.  You should never be able to delete an entry from Recent - only save it.  Therefore, you should never see a trashcan icon in the Recent section, only in the Saved section.

And as a side note, we should limit the number of Recent entries that we save to the last 20 or something, and purge older ones as newer calls are made

**Comment by davehorton** [comment]
Please change the title from "Jambonz Webrtc Client" to "Jambonz Webphone".

Also, for now hide the "Get help" icon and text since we don't have it hooked up to anything yet

**Comment by xquanluu** [comment]
I fixed all above comments

**Review by davehorton — APPROVED** [review]

**Pull request merged**
